package com.bwsi.joborder;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class globalvar {
private static globalvar mostCurrent = new globalvar();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 public anywheresoftware.b4a.keywords.Common __c = null;
public static int _dbversion = 0;
public static String _apicontroller = "";
public static String _baseurl = "";
public static String _requesttokenurl = "";
public static String _refreshtokenurl = "";
public static String _clientid = "";
public static String _clientsecretkey = "";
public static anywheresoftware.b4a.objects.CSBuilder _cstitle = null;
public static anywheresoftware.b4a.objects.CSBuilder _cssubtitle = null;
public static anywheresoftware.b4a.keywords.constants.TypefaceWrapper _font = null;
public static anywheresoftware.b4a.keywords.constants.TypefaceWrapper _fontbold = null;
public static double _pricolor = 0;
public static double _seccolor = 0;
public static double _poscolor = 0;
public static double _negcolor = 0;
public static double _neutralcolor = 0;
public static double _bluecolor = 0;
public static double _greencolor = 0;
public static double _greencolor2 = 0;
public static double _redcolor = 0;
public static double _yellowcolor = 0;
public static double _graycolor = 0;
public static double _yellowcolor2 = 0;
public static adr.stringfunctions.stringfunctions _sf = null;
public b4a.example.dateutils _dateutils = null;
public com.bwsi.joborder.main _main = null;
public com.bwsi.joborder.starter _starter = null;
public com.bwsi.joborder.camera _camera = null;
public com.bwsi.joborder.mainscreen _mainscreen = null;
public com.bwsi.joborder.notif _notif = null;
public com.bwsi.joborder.misc _misc = null;
public com.bwsi.joborder.dbutils _dbutils = null;
public com.bwsi.joborder.httputils2service _httputils2service = null;
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 3;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 6;BA.debugLine="Public DBVersion As Int : DBVersion = 1";
_dbversion = 0;
 //BA.debugLineNum = 6;BA.debugLine="Public DBVersion As Int : DBVersion = 1";
_dbversion = (int) (1);
 //BA.debugLineNum = 7;BA.debugLine="Public APIController As String = \"ApiController\"";
_apicontroller = "ApiController";
 //BA.debugLineNum = 8;BA.debugLine="Public BaseURL As String : BaseURL = \"https://rci";
_baseurl = "";
 //BA.debugLineNum = 8;BA.debugLine="Public BaseURL As String : BaseURL = \"https://rci";
_baseurl = "https://rcis-dev.bwsi.com.ph/api/";
 //BA.debugLineNum = 9;BA.debugLine="Public RequestTokenURL As String : RequestTokenUR";
_requesttokenurl = "";
 //BA.debugLineNum = 9;BA.debugLine="Public RequestTokenURL As String : RequestTokenUR";
_requesttokenurl = "https://rcis-dev.bwsi.com.ph/oauth/token";
 //BA.debugLineNum = 10;BA.debugLine="Public RefreshTokenURL As String : RefreshTokenUR";
_refreshtokenurl = "";
 //BA.debugLineNum = 10;BA.debugLine="Public RefreshTokenURL As String : RefreshTokenUR";
_refreshtokenurl = "https://rcis-dev.bwsi.com.ph/oauth/token";
 //BA.debugLineNum = 12;BA.debugLine="Public ClientID As String : ClientID = \"1\"";
_clientid = "";
 //BA.debugLineNum = 12;BA.debugLine="Public ClientID As String : ClientID = \"1\"";
_clientid = "1";
 //BA.debugLineNum = 13;BA.debugLine="Public ClientSecretKey As String : ClientSecretKe";
_clientsecretkey = "";
 //BA.debugLineNum = 13;BA.debugLine="Public ClientSecretKey As String : ClientSecretKe";
_clientsecretkey = "SWSU335vhTSvDIIPhYD2xeGzQq7kK9fNWoxdt3xt";
 //BA.debugLineNum = 15;BA.debugLine="Public csTitle, csSubTitle As CSBuilder";
_cstitle = new anywheresoftware.b4a.objects.CSBuilder();
_cssubtitle = new anywheresoftware.b4a.objects.CSBuilder();
 //BA.debugLineNum = 17;BA.debugLine="Public Font As Typeface = Typeface.LoadFromAssets";
_font = new anywheresoftware.b4a.keywords.constants.TypefaceWrapper();
_font = (anywheresoftware.b4a.keywords.constants.TypefaceWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.keywords.constants.TypefaceWrapper(), (android.graphics.Typeface)(anywheresoftware.b4a.keywords.Common.Typeface.LoadFromAssets("myfont.ttf")));
 //BA.debugLineNum = 18;BA.debugLine="Public FontBold As Typeface = Typeface.LoadFromAs";
_fontbold = new anywheresoftware.b4a.keywords.constants.TypefaceWrapper();
_fontbold = (anywheresoftware.b4a.keywords.constants.TypefaceWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.keywords.constants.TypefaceWrapper(), (android.graphics.Typeface)(anywheresoftware.b4a.keywords.Common.Typeface.LoadFromAssets("myfont_bold.ttf")));
 //BA.debugLineNum = 20;BA.debugLine="Public PriColor = 0xFF0099cc As Double 'primary";
_pricolor = 0xff0099cc;
 //BA.debugLineNum = 21;BA.debugLine="Public SecColor = 0xFF7FBDFF As Double";
_seccolor = 0xff7fbdff;
 //BA.debugLineNum = 23;BA.debugLine="Public PosColor = 0xFF007BFF As Double";
_poscolor = 0xff007bff;
 //BA.debugLineNum = 24;BA.debugLine="Public NegColor = 0xFFDC3545 As Double";
_negcolor = 0xffdc3545;
 //BA.debugLineNum = 25;BA.debugLine="Public NeutralColor = 0xFF7FBDFF As Double";
_neutralcolor = 0xff7fbdff;
 //BA.debugLineNum = 27;BA.debugLine="Public BlueColor = 0xFF17A2B7 As Double 'info col";
_bluecolor = 0xff17a2b7;
 //BA.debugLineNum = 28;BA.debugLine="Public GreenColor = 0xFF28A745 As Double 'success";
_greencolor = 0xff28a745;
 //BA.debugLineNum = 29;BA.debugLine="Public GreenColor2 = 0xFF188731 As Double 'succes";
_greencolor2 = 0xff188731;
 //BA.debugLineNum = 30;BA.debugLine="Public RedColor = 0xFFDC3545 As Double 'danger co";
_redcolor = 0xffdc3545;
 //BA.debugLineNum = 31;BA.debugLine="Public YellowColor = 0xFFFFC107 As Double 'warnin";
_yellowcolor = 0xffffc107;
 //BA.debugLineNum = 32;BA.debugLine="Public GrayColor = 0xFF62789E As Double";
_graycolor = 0xff62789e;
 //BA.debugLineNum = 33;BA.debugLine="Public YellowColor2 = 0xFFE5B040 As Double 'warni";
_yellowcolor2 = 0xffe5b040;
 //BA.debugLineNum = 34;BA.debugLine="Public SF As StringFunctions";
_sf = new adr.stringfunctions.stringfunctions();
 //BA.debugLineNum = 36;BA.debugLine="End Sub";
return "";
}
}
